dataset: 
  train_csv       : dataset/train.csv
  test_csv        : dataset/test.csv
  validation_csv  : dataset/validation.csv
  root_img_dir    : /media/phuntsho/DataStorage/plotreel-dataset/
  
augmentation:
  width           : 400
  height          : 300
  rotation        : 360
  horizontal_flip : 0.5
  vertical_flip   : 0.5
  zoom_range      : 0
  shear_range     : 0
  gaussian        : 0.1

model: 
  name        : inception_v3
  optimizer   : Adam
  loss        : BCEWithLogitsLoss
  scheduler   : cycliclr_exp_range
  lr          : 0.001
  batch       : 32
  classes     : 2
  train_size  : 0.9
  seed        : 30
  epochs      : 30
  save_model  : models
  momentum    : 0.9
  identifier  : 0 

test: 
  name        : resnet50_Adam_lr_0.001_epoch_30_day_27_month_03_time_20_13.pt
  model_path  : models/


wandb: 
  use         : True
  wandb_group : train


