dataset: 
  train_csv     : /home/phuntsho/Desktop/plot-finder/plot-finder/dataset/train.csv
  test_csv      : /home/phuntsho/Desktop/plot-finder/plot-finder/dataset/test.csv
  validation_csv:  /home/phuntsho/Desktop/plot-finder/plot-finder/dataset/validation.csv
  root_img_dir  :  /media/phuntsho/DataStorage/plotreel-dataset/
  
augmentation:
  width             : 400
  height            : 300
  rotation          : 360
  horizontal_flip   : 0.5
  vertical_flip     : 0.5
  zoom_range        : 0
  shear_range       : 0
  gaussian          : 0.1

model: 
  # name: inception_v3
  name        : resnet50
  optimizer   : Adam
  loss        : CrossEntropyLoss
  scheduler   : linear
  lr          : 0.001
  batch       : 32
  classes     : 2
  train_size  : 0.9
  seed        : 1
  epochs      : 10
  save_model  : /home/phuntsho/Desktop/plot-finder/plot-finder/models
  momentum    : 0.9

test: 
  name        : resnet50_Adam_lr_0.001_epoch_20.pt
  model_path  : /home/phuntsho/Desktop/plot-finder/plot-finder/models/


wandb: 
  use           : True
  wandb_group   : cross_entropy_loss



"""
models_available: 
  resnet50
  inception_v3
  swin_transfomer

loss_available: 
  BCEWithLogitsLoss
  CrossEntropy
"""